version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_db
      - AUDIT_GRPC_URL=audit-service:50051
    depends_on:
      - user-db
      - audit-service

  audit-db:
    image: postgres:15
    container_name: audit-db
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - audit_db_data:/var/lib/postgresql/data

  audit-service:
    build: ./audit-service
    container_name: audit-service
    ports:
      - '50051:50051'
    environment:
      - DB_HOST=audit-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=audit_db
    depends_on:
      - audit-db

volumes:
  user_db_data:
  audit_db_data:
